name: "Lint Markdown"

on:
  push:
    paths-ignore:
    - .*
    - LICENSE.md
  pull_request:
    paths-ignore:
    - .*
    - LICENSE.md

jobs:
  lint-changelog:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run markdownlint
      uses: docker://avtodev/markdown-lint:master
      with:
        config: '.github/workflows/markdownlint.json'
        args: '*.md'
